import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Kanye({res}) {
  console.log(res);
  return (
    <div className={styles.wrapper}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Click to see Kanyes Bullshit
        </h1>

        <div className={styles.grid}>

          <a className={styles.card}>
            <h2>{res.quote}</h2>
          </a>

          <img className={styles.img}  src='https://i.pinimg.com/736x/d8/58/3f/d8583fe287203342606b495f3045209a.jpg' />

        <button className={styles.btn} type='submit' onClick={() => {
          window.location.reload();
        }}>Surprise Me!</button>

        </div>
      </main>

    </div>
  )
};

Kanye.getInitialProps = async () => {
  const res = await fetch('https://api.kanye.rest')
  const data = await res.json()
  return {res:data}
}



